version: '2.1'
services:
  heimdall-openemail:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=${TZ}
    volumes:
      - ./config/heimdall:/config
    restart: always
    networks:
      openemail-network:
        aliases:
          - heimdall

  unbound-openemail:
    image: openemail/unbound:latest
    container_name: unbound
    command: /usr/sbin/unbound
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro
    restart: always
    tty: true
    networks:
      openemail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  mysql-openemail:
    image: openemail/mariadb:latest
    container_name: mysql
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=openemail,nextcloud,rainloop,roundcube
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      openemail-network:
        aliases:
          - mysql

  phpmyadmin-openemail:
    image: openemail/phpmyadmin:latest
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: always
    environment:
      - TZ=${TZ}
      - PHPMYADMIN_DB_HOSTS=mysql
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - phpmyadmin

  roundcube-openemail:
    image: openemail/roundcube:latest
    container_name: roundcube
    environment:
      - TZ=${TZ}
      - ROUNDCUBEMAIL_DEFAULT_HOST=dovecot
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
      - ROUNDCUBEMAIL_SMTP_PORT=587
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=${DBUSER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DBPASS}
      - ROUNDCUBEMAIL_DB_NAME=roundcube
    volumes:
      - ./data/roundcube/config/:/var/roundcube/config/
    depends_on:
      - mysql-openemail
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - roundcube

  rainloop-openemail:
    image: openemail/rainloop:latest
    container_name: rainloop
    links:
      - mysql-openemail
    environment:
      - TZ=${TZ}
      - UPLOAD_MAX_SIZE=25M
      - LOG_TO_STDOUT=true
      - MEMORY_LIMIT=128M
    volumes:
     - ./data/rainloop:/rainloop/data
    depends_on:
     - mysql-openemail
    dns:
     - ${IPV4_NETWORK:-172.22.1}.254
    networks:
     openemail-network:
       aliases:
         - rainloop

  nextcloud-openemail:
   image: openemail/nextcloud:latest
   container_name: nextcloud
   environment:
     - PUID=1001
     - PGID=1001
     - TZ=${TZ}
   volumes:
     - ./data/nextcloud/config:/config
     - ./data/nextcloud/data:/data
   restart: always
   depends_on:
     - mysql-openemail
   dns:
     - ${IPV4_NETWORK:-172.22.1}.254
   networks:
     openemail-network:
       aliases:
         - nextcloud

  redis-openemail:
    image: openemail/redis:latest
    container_name: redis
    volumes:
      - redis-vol-1:/data/
    restart: always
    environment:
      - TZ=${TZ}
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
         - redis
         - redis-mailcow

  clamd-openemail:
    image: openemail/clamd:latest
    container_name: clamd
    restart: always
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - clamd

  rspamd-openemail:
    image: openemail/rspamd:latest
    container_name: rspamd
    stop_grace_period: 30s
    depends_on:
      - nginx-openemail
      - dovecot-openemail
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    hostname: rspamd
    networks:
      openemail-network:
        aliases:
          - rspamd

  php-fpm-openemail:
    image: openemail/php-fpm:latest
    container_name: phpfpm
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis-openemail
    volumes:
      - ./data/web:/web:rw
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/sogo/:/etc/sogo/
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
      - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/
      - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf
      - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini
      - ./data/assets/templates:/tpls
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
      - API_KEY=${API_KEY:-invalid}
      - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-openemail}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - phpfpm

  sogo-openemail:
    image: openemail/sogo:latest
    container_name: sogo
    environment:
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - LOG_LINES=${LOG_LINES:-9999}
      - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - SOGO_EXPIRE_SESSION=${SOGO_EXPIRE_SESSION:-480}
    volumes:
      - ./data/conf/sogo/:/etc/sogo/
      - ./data/web/inc/init_db.inc.php:/init_db.inc.php
      - ./data/conf/sogo/custom-sogo.js:/usr/lib/GNUstep/SOGo/WebServerResources/js/custom-sogo.js
      - mysql-socket-vol-1:/var/run/mysqld/
      - sogo-web-vol-1:/sogo_web
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.248
        aliases:
          - sogo

  dovecot-openemail:
    image: openemail/dovecot:latest
    container_name: dovecot
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./data/conf/dovecot:/etc/dovecot
      - ./data/assets/ssl:/etc/ssl/mail/:ro
      - ./data/conf/sogo/:/etc/sogo/
      - ./data/conf/phpfpm/sogo-sso/:/etc/phpfpm/
      - vmail-vol-1:/var/vmail
      - vmail-attachments-vol-1:/var/attachments
      - crypt-vol-1:/mail_crypt/
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom
      - ./data/assets/templates:/templates
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - TZ=${TZ}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-1440}
      - ACL_ANYONE=${ACL_ANYONE:-disallow}
      - SKIP_SOLR=${SKIP_SOLR:-y}
      - MAILDIR_SUB=${MAILDIR_SUB:-}
    ports:
      - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
      - "${IMAP_PORT:-143}:143"
      - "${IMAPS_PORT:-993}:993"
      - "${POP_PORT:-110}:110"
      - "${POPS_PORT:-995}:995"
      - "${SIEVE_PORT:-4190}:4190"
    restart: always
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    hostname: ${OPENEMAIL_HOSTNAME}
    networks:
      openemail-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.250
        aliases:
          - dovecot

  postfix-openemail:
    image: openemail/postfix:latest
    container_name: postfix
    hostname: postfix
    volumes:
      - ./data/conf/postfix:/opt/postfix/conf
      - ./data/assets/ssl:/etc/ssl/mail/:ro
      - postfix-vol-1:/var/spool/postfix
      - crypt-vol-1:/var/lib/zeyple
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
    cap_add:
      - NET_BIND_SERVICE
    ports:
      - "${SMTP_PORT:-25}:25"
      - "${SMTPS_PORT:-465}:465"
      - "${SUBMISSION_PORT:-587}:587"
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    hostname: ${OPENEMAIL_HOSTNAME}
    networks:
      openemail-network:
        aliases:
          - postfix

  memcached-openemail:
    image: memcached:alpine
    container_name: memcached
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - memcached

  nginx-openemail:
    depends_on:
      - sogo-openemail
      - php-fpm-openemail
      - redis-openemail
    image: nginx:mainline-alpine
    container_name: nginx
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/templates/listen_plain.template > /etc/nginx/conf.d/listen_plain.active &&
      envsubst < /etc/nginx/conf.d/templates/listen_ssl.template > /etc/nginx/conf.d/listen_ssl.active &&
      envsubst < /etc/nginx/conf.d/templates/server_name.template > /etc/nginx/conf.d/server_name.active &&
      envsubst < /etc/nginx/conf.d/templates/sogo.template > /etc/nginx/conf.d/sogo.active &&
      envsubst < /etc/nginx/conf.d/templates/sogo_eas.template > /etc/nginx/conf.d/sogo_eas.active &&
      . /etc/nginx/conf.d/templates/sogo.auth_request.template.sh > /etc/nginx/conf.d/sogo_proxy_auth.active &&
      nginx -qt &&
      until ping phpfpm -c1 > /dev/null; do sleep 1; done &&
      until ping sogo -c1 > /dev/null; do sleep 1; done &&
      until ping redis -c1 > /dev/null; do sleep 1; done &&
      until ping rspamd -c1 > /dev/null; do sleep 1; done &&
      exec nginx -g 'daemon off;'"
    environment:
      - HTTPS_PORT=${HTTPS_PORT:-443}
      - HTTP_PORT=${HTTP_PORT:-80}
      - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - TZ=${TZ}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
    volumes:
      - ./data/web:/web:ro
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro
      - ./data/assets/ssl/:/etc/ssl/mail/:ro
      - ./data/conf/nginx/:/etc/nginx/conf.d/:rw
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro
      - sogo-web-vol-1:/usr/lib/GNUstep/SOGo/
    ports:
      - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
      - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - nginx

  acme-openemail:
    depends_on:
      - nginx-openemail
    image: openemail/acme:latest
    container_name: acme
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - ADDITIONAL_SAN=${ADDITIONAL_SAN}
      - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - SKIP_IP_CHECK=${SKIP_IP_CHECK:-n}
      - SKIP_HTTP_VERIFICATION=${SKIP_HTTP_VERIFICATION:-n}
      - ONLY_OPENEMAIL_HOSTNAME=${ONLY_OPENEMAIL_HOSTNAME:-n}
      - LE_STAGING=${LE_STAGING:-n}
      - TZ=${TZ}
    volumes:
      - ./data/web/.well-known/acme-challenge:/var/www/acme:rw
      - ./data/assets/ssl:/var/lib/acme/:rw
      - ./data/assets/ssl-example:/var/lib/ssl-example/:ro
      - mysql-socket-vol-1:/var/run/mysqld/
    restart: always
    networks:
      openemail-network:
        aliases:
          - acme

  netfilter-openemail:
    image: openemail/netfilter:latest
    container_name: netfilter
    stop_grace_period: 30s
    depends_on:
      - dovecot-openemail
      - postfix-openemail
      - sogo-openemail
      - php-fpm-openemail
      - redis-openemail
    restart: always
    privileged: true
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SNAT_TO_SOURCE=${SNAT_TO_SOURCE:-n}
      - SNAT6_TO_SOURCE=${SNAT6_TO_SOURCE:-n}
    network_mode: "host"
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      - /lib/modules:/lib/modules:ro

  watchdog-openemail:
    image: openemail/watchdog:latest
    container_name: watchdog
    volumes:
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/assets/ssl:/etc/ssl/mail/:ro
    restart: always
    environment:
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - USE_WATCHDOG=${USE_WATCHDOG:-n}
      - WATCHDOG_NOTIFY_EMAIL=${WATCHDOG_NOTIFY_EMAIL}
      - WATCHDOG_NOTIFY_BAN=${WATCHDOG_NOTIFY_BAN:-y}
      - OPENEMAIL_HOSTNAME=${OPENEMAIL_HOSTNAME}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - IP_BY_DOCKER_API=${IP_BY_DOCKER_API:-0}
      - CHECK_UNBOUND=${CHECK_UNBOUND:-1}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
      - SKIP_LETS_ENCRYPT=${SKIP_LETS_ENCRYPT:-n}
      - HTTPS_PORT=${HTTPS_PORT:-443}
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
         - watchdog

  dockerapi-openemail:
    image: openemail/dockerapi:latest
    restart: always
    container_name: dockerapi
    oom_kill_disable: true
    environment:
      - DBROOT=${DBROOT}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      openemail-network:
        aliases:
          - dockerapi

  solr-openemail:
    image: openemail/solr:latest
    container_name: solr
    restart: always
    volumes:
      - solr-vol-1:/opt/solr/server/solr/dovecot-fts/data
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - TZ=${TZ}
      - SOLR_HEAP=${SOLR_HEAP:-1024}
      - SKIP_SOLR=${SKIP_SOLR:-y}
    networks:
      openemail-network:
        aliases:
          - solr

  olefy-openemail:
    image: openemail/olefy:latest
    restart: always
    container_name: olefy
    environment:
      - OLEFY_BINDADDRESS=0.0.0.0
      - OLEFY_BINDPORT=10055
      - OLEFY_TMPDIR=/tmp
      - OLEFY_PYTHON_PATH=/usr/bin/python3
      - OLEFY_OLEVBA_PATH=/usr/bin/olevba3
      - OLEFY_LOGLVL=20
      - OLEFY_MINLENGTH=500
      - OLEFY_DEL_TMP=1
    networks:
      openemail-network:
        aliases:
          - olefy

  ipv6nat-openemail:
    depends_on:
      - unbound-openemail
      - mysql-openemail
      - redis-openemail
      - clamd-openemail
      - rspamd-openemail
      - php-fpm-openemail
      - sogo-openemail
      - dovecot-openemail
      - postfix-openemail
      - memcached-openemail
      - nginx-openemail
      - acme-openemail
      - netfilter-openemail
      - watchdog-openemail
      - dockerapi-openemail
      - solr-openemail
    image: robbertkl/ipv6nat
    container_name: ipv6nat
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro

networks:
  openemail-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-openemail
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}

volumes:
  # Storage for email files
  vmail-vol-1:
  # Storage for attachments (deduplicated)
  vmail-attachments-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  solr-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  sogo-web-vol-1:
