  roundcube-openemail:
    image: openemail/roundcube:latest
    container_name: roundcube
    hostname: rc.${OPENEMAIL_DOMAIN}
    environment:
      - TZ=${TZ}
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.softlineglobal.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      - ROUNDCUBEMAIL_SMTP_SERVER=postfix
      - ROUNDCUBEMAIL_SMTP_PORT=588
      - ROUNDCUBEMAIL_PLUGINS=archive,zipdownload,password
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=25M
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=mysql
      - ROUNDCUBEMAIL_DB_PORT=3306
      - ROUNDCUBEMAIL_DB_USER=${DBUSER}
      - ROUNDCUBEMAIL_DB_PASSWORD=${DBPASS}
      - ROUNDCUBEMAIL_DB_NAME=${RCDBNAME}
    volumes:
      # - ./data/conf/roundcube/config.inc.php:/var/www/html/config/config.inc.php
      - ./data/roundcube/config/:/var/www/html/config/
    depends_on:
      - mysql-openemail
    restart: always
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      openemail-network:
        aliases:
          - roundcube

  
